# The Docker image that will be used to build your app
image: python:3.10-slim
pages:
  script:
    - pip3 install -r docs/source/requirements.txt
    - sphinx-build -b html docs/source public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
